services:
  website-compare-app:
    container_name: website-compare-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@website-compare-db:5432/${DB_NAME}?schema=public
    volumes:
      - ./public/screenshots:/app/public/screenshots:rw
      # - ./prisma:/app/prisma
    command: sh -c "npx prisma migrate deploy"
    depends_on:
      - website-compare-db
    networks:
      - website-compare-network

  website-compare-db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - website-compare-network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./public/screenshots:/var/www/html/screenshots:rw
    depends_on:
      - website-compare-app
    networks:
      - website-compare-network

networks:
  website-compare-network:
    driver: bridge

volumes:
  postgres_data:
